logging:
  level:
    # 这里设置的日志级别优先于log4j2.xml文件Loggers中的日志级别。
    com.orangeforms: info

server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 100
      min-spare: 10
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

# spring相关配置
spring:
  application:
    name: application-webadmin
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    converters:
      preferred-json-mapper: fastjson
  freemarker:
    template-loader-path: classpath:/template/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl

flowable:
  async-executor-activate: false
  database-schema-update: false

mybatis-plus:
  mapper-locations: classpath:com/orangeforms/webadmin/*/dao/mapper/*Mapper.xml,com/orangeforms/common/log/dao/mapper/*Mapper.xml,com/orangeforms/common/online/dao/mapper/*Mapper.xml,com/orangeforms/common/flow/dao/mapper/*Mapper.xml
  type-aliases-package: com.orangeforms.webadmin.*.model,com.orangeforms.common.log.model,com.orangeforms.common.online.model,com.orangeforms.common.flow.model
  global-config:
    db-config:
      logic-delete-value: -1
      logic-not-delete-value: 1

# 自动分页的配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql

common-core:
  # 可选值为 mysql / postgresql
  databaseType: mysql

common-online:
  # 可选值为 mysql / postgresql
  databaseType: mysql
  # 注意不要以反斜杠(/)结尾。
  operationUrlPrefix: /admin/online
  # 在线表单业务数据上传资源路径
  uploadFileBaseDir: ./zz-resource/upload-files/online
  # 如果为false，OnlineOperationController中的接口将不能使用。
  operationEnabled: true

common-online-api:
  # 注意不要以反斜杠(/)结尾。
  urlPrefix: /admin/online
  # 下面的url列表，请保持反斜杠(/)结尾。
  viewUrlList:
  - ${common-online.operationUrlPrefix}/onlineOperation/viewByDatasourceId/
  - ${common-online.operationUrlPrefix}/onlineOperation/viewByOneToManyRelationId/
  - ${common-online.operationUrlPrefix}/onlineOperation/listByDatasourceId/
  - ${common-online.operationUrlPrefix}/onlineOperation/listByOneToManyRelationId/
  - ${common-online.operationUrlPrefix}/onlineOperation/exportByDatasourceId/
  - ${common-online.operationUrlPrefix}/onlineOperation/exportByOneToManyRelationId/
  - ${common-online.operationUrlPrefix}/onlineOperation/downloadDatasource/
  - ${common-online.operationUrlPrefix}/onlineOperation/downloadOneToManyRelation/
  editUrlList:
  - ${common-online.operationUrlPrefix}/onlineOperation/addDatasource/
  - ${common-online.operationUrlPrefix}/onlineOperation/addOneToManyRelation/
  - ${common-online.operationUrlPrefix}/onlineOperation/updateDatasource/
  - ${common-online.operationUrlPrefix}/onlineOperation/updateOneToManyRelation/
  - ${common-online.operationUrlPrefix}/onlineOperation/deleteDatasource/
  - ${common-online.operationUrlPrefix}/onlineOperation/deleteOneToManyRelation/
  - ${common-online.operationUrlPrefix}/onlineOperation/deleteBatchDatasource/
  - ${common-online.operationUrlPrefix}/onlineOperation/deleteBatchOneToManyRelation/
  - ${common-online.operationUrlPrefix}/onlineOperation/uploadDatasource/
  - ${common-online.operationUrlPrefix}/onlineOperation/uploadOneToManyRelation/

common-flow:
  # 请慎重修改urlPrefix的缺省配置，注意不要以反斜杠(/)结尾。如必须修改其他路径，请同步修改数据库脚本。
  urlPrefix: /admin/flow

swagger:
  # 当enabled为false的时候，则可禁用swagger。
  enabled: true
  # 工程的基础包名。
  basePackage: com.orangeforms
  # 工程服务的基础包名。
  serviceBasePackage: com.orangeforms.webadmin
  title: 橙单单体服务工程
  description: 橙单单体服务工程详情
  version: 1.0

datafilter:
  tenant:
    # 对于单体服务，该值始终为false。
    enabled: false
  dataperm:
    enabled: true
    # 在拼接数据权限过滤的SQL时，我们会用到sys_dept_relation表，该表的前缀由此配置项指定。
    # 如果没有前缀，请使用 "" 。
    deptRelationTablePrefix: zz_

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    # 与中间件相关的健康详情也会被展示
    health:
      show-details: always
    configprops:
      # 在/actuator/configprops中，所有包含password的配置，将用 * 隐藏。
      # 如果不想隐藏任何配置项的值，可以直接使用如下被注释的空值。
      # keys-to-sanitize:
      keys-to-sanitize: password
  server:
    base-path: "/"

aj:
  captcha:
    # 缓存local/redis..
    cache-type: redis
    # 验证码类型default两种都实例化。
    type: default
    # 右下角水印文字(我的水印)
    water-mark: 我的水印
    #点选字体样式 默认Font.BOLD
    font-style: 1
    #点选字体字体大小
    font-size: 25
    # 支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/jigsaw
    jigsaw: classpath:images/jigsaw
    # 支持项目路径,以classpath:开头,取resource目录下路径,例：classpath:images/pic-click
    pic-click: classpath:images/pic-click
    history-data-clear-enable: false
    # 接口请求次数一分钟限制是否开启 true|false
    req-frequency-limit-enable: false
    # 验证失败5次，get接口锁定
    req-get-lock-limit: 5
    # 验证失败后，锁定时间间隔,s
    req-get-lock-seconds: 360
    # get接口一分钟内请求数限制
    req-get-minute-limit: 30
    # check接口一分钟内请求数限制
    req-check-minute-limit: 30
    # verify接口一分钟内请求数限制
    req-verify-minute-limit: 60
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 2
