logging:
  level:
    # 这里设置的日志级别优先于log4j2.xml文件Loggers中的日志级别。
    com.orange.demo: info

server:
  port: 9002

application:
  # 缺省的文件上传根目录。
  uploadFileBaseDir: ./zz-resource/upload-files/stats
  # 每个微服务的url目录上下文，如(/admin/upms)，通常和网关的路由path一致。
  serviceContextPath: /admin/stats
  # 是否忽略远程调用中出现的任何错误，包括逻辑异常和系统异常。
  # 通常在调试和测试阶段设置为false，以便及时发现问题。
  ignoreRpcError: false

sequence:
  # 是否使用基于美团Leaf的分布式Id生成器。
  advanceIdGenerator: true
  # 多个zk服务之间逗号分隔。
  zkAddress: localhost:2181
  # 与本机的ip一起构成zk中标识不同服务实例的key值。
  idPort: 19002
  # zk中生成WorkNode的路径。不同的业务可以使用不同的路径，以免冲突。
  zkPath: com/orange/demo

# mybatis的基本配置
mybatis:
  mapperLocations: classpath:com/orange/demo/*/dao/mapper/*Mapper.xml
  typeAliasesPackage: com.orange.demo.*.model

mapper:
  mappers: tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.additional.insert.InsertListMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: false
  params: count=countSql

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/zzdemo-single?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: stats
      initialSize: 10
      minIdle: 10
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      filters: stat,wall
      useGlobalDataSourceStat: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/actuator/*"
      stat-view-servlet:
        enabled: true
        urlPattern: /druid/*
        resetEnable: true
