version: '3.2'

services:

  nacos:
    image: nacos/nacos-server:1.3.1
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    volumes:
      - ./logs/nacos/:/home/nacos/logs
      - ./data/nacos/:/home/nacos/data
    ports:
      - "8848:8848"
    networks:
      - zz-test

  redis:
    container_name: redis
    build:
      context: services/redis/
      args:
        - REDIS_VER=4
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./data/redis:/data:rw
      - ./logs/redis:/var/log/:rw
    networks:
      - zz-test

  zookeeper:
    image: zookeeper:3.5.5
    ports:
      - "2181:2181"
    volumes:
      - ./logs/zookeeper/:/data
      - ./data/zookeeper/:/datalog
    networks:
      - zz-test

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - ./data/kafka/:/kafka
    networks:
      - zz-test
    depends_on:
      - zookeeper

  sentinel:
    image: bladex/sentinel-dashboard
    ports:
      - "8858:8858"
    networks:
      - zz-test

  minio:
    image: minio/minio:latest
    environment:
      # spring boot服务中的配置项需要与该值相同。
      # nginx访问页面的登录名和密码。密码不能少于8个字符。
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=admin123456
    volumes:
      - ./data/minio:/data
      - ./services/minio/config:/root/.minio
    ports:
      # 对主机暴露19000接口，nginx需要将请求导入该端口号。
      - "19000:9000"
    command: server /data

networks:
  zz-test:
    driver: bridge
